APP_NAME = "Cooking Assistant Demo"
DEFAULT_MODEL = "gpt-5.4-nano"
DEFAULT_RECIPE_PATH = "recipes/scrambled_eggs.json"
DEFAULT_TIMER_WARN_AT_SECONDS = 10
DEFAULT_CONTEXT_FRAME_COUNT = 3
DEFAULT_CONTEXT_MAX_AGE_SECONDS = 12.0
DEFAULT_AUDIO_SAMPLE_RATE = 24000
DEFAULT_AUDIO_CHANNELS = 1
